### ISSUE TITLE
Slightly related: beemuse.com DNS

### ISSUE THREAD

**Issue by psofe** [itmustbe/beemuse-paper#1]
The Bower manifest does not contain contact information, and the beemuse.com DNS is down.  Just passing this along.

Thanks for the wonderful tool and/or maintenance!

**Comment by itmustbe** [comment]
I honestly didn't know anyone was still using this :) Hence I took the website beemuse.com down last week after I migrated to a new server. I should probably tidy up these related repos here and condense everything into the main itmustbe/beemuse repo. Thanks for letting me know of your interest!

**Comment by psofe** [comment]
I make frequent use of the library and can host the site if need be.

Thanks again!

**Comment by itmustbe** [comment]
Give me a day or two and I'll put the beemuse.com site back online, as well as review all the code here again (I used to use this library, but haven't had a call to for awhile). I'm assuming it's the paper component specifically that you use often?

**Comment by psofe** [comment]
Awesome.  Yes, beemuse-paper is what I most often use, but if components play-well together, I'm likely to use the others as well.

**Comment by itmustbe** [comment]
The beemuse.com website is back up :) I may not get to reviewing the code for a bit still (with work) but it is something I plan to do, especially since it's helping others too!
